### ISSUE TITLE
The "Perl 5.34 rebuild" bumps were rebuilt with Perl 5.32 in ELN

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#57]
Many Perl packages were bumped as "Perl 5.34 rebuild" and rebuilt with Perl 5.34 in Fedora Rawhide, but they were rebuilt with Perl 5.32 in Fedora ELN.

**Comment by sgallagher** [comment]
Thanks for letting us know; I'll try to have a look at this next week.

**Comment by sgallagher** [comment]
The underlying reason here is that Perl 5.34 is FTBFS in ELN (faiing tests), so I'll need some help from the Perl experts. Or possibly the toolchain, if it turns out the problem is with different compiler configuration.

**Comment by sgallagher** [comment]
For posterity:
```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.892cVt
+ umask 022
+ cd /builddir/build/BUILD
+ cd perl-5.34.0
+ LD_PRELOAD=/builddir/build/BUILDROOT/perl-5.34.0-477.eln110.x86_64/usr/lib64/perl5/CORE/libperl.so
+ LD_LIBRARY_PATH=/builddir/build/BUILDROOT/perl-5.34.0-477.eln110.x86_64/usr/lib64/perl5/CORE
+ PERL5LIB=/builddir/build/BUILDROOT/perl-5.34.0-477.eln110.x86_64/usr/lib64/perl5:/builddir/build/BUILDROOT/perl-5.34.0-477.eln110.x86_64/usr/share/perl5
+ /builddir/build/BUILDROOT/perl-5.34.0-477.eln110.x86_64/usr/bin/perl -I/lib regen/lib_cleanup.pl
Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xed00080, needed 0xeb00080)
error: Bad exit status from /var/tmp/rpm-tmp.892cVt (%check)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.892cVt (%check)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.9/site-packages/mockbuild/util.py", line 600, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/perl.spec
```

**Comment by hroncok** [comment]
I'd say the underlying reason here is the build order / bootstrap issue in ELN wrt side tags.

**Comment by sgallagher** [comment]
I think this should be mostly sorted out now. I did a mini-mass-rebuild of the affected packages in ELN today.

**Comment by hroncok** [comment]
Thanks. Just a heads up that this might also happen with Python 3.10.

**Comment by sgallagher** [comment]
Yeah, I'm aware of it (and it probably will).
